### ISSUE TITLE
Redmine 4.0 fix

### ISSUE THREAD

**Issue by FabriceSalvaire** [bluezio/redmine_wiki_backlinks#9]
in **app/controllers/wiki_links_controller.rb** : **before_filter** must be replaced by **before_action**

else seems to work

excepted  **Parsed #{nwikis} wikis successfully**

**Comment by bluezio** [comment]
I've made the fix you suggest. Please confirm if it is working now: I am not sure if I understand the part about the "Parsed ..." message. Unfortunately, I don't have a Redmine installation at the moment to try it on.

**Comment by FabriceSalvaire** [comment]
Fix is right. I think ' #{nwikis} ' is not evaluated but it is a minor issue.

**Comment by bluezio** [comment]
Thanks for confirming - I am closing the issue. If you find out what's the problem with '#{nwikis}', feel free to raise another issue or send a pull request :-).
